services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # target: test
    depends_on:
      - vault
      - postgres
    
    env_file:
      - tests/.env

  vault:
    image: hashicorp/vault
    # environment:
    #   - VAULT_
    cap_add:
      # allows a process to lock memory pages in RAM
      # so that it gets written to disk only when the process is killed
      - IPC_LOCK
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/file
    command: "vault server -config=/vault/config/vault-config.json"

  postgres:
    image: postgres:18-alpine3.22
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
