name: Test the Vault Injector

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            vault:
                image: hashicorp/vault:latest
                options: --cap-add=IPC_LOCK -v ./vault/config:/vault/config -v ./vault/data:/vault/file
                ports:
                    - 8200:8200

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Install dependencies
              run: |
                  uv sync

            - name: Run tests
              run: |
                  uv run pytest
