name: Linting

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install the latest version of ruff
              uses: astral-sh/ruff-action@v3
            #   with:
            #       # define this to override the default behaviour of check
            #       version: "latest"

            - name: Ruff check
              run: ruff check --fix

            - name: Ruff format
              run: ruff format
